### ISSUE TITLE
Can't use optional with sanitizers.

### ISSUE THREAD

**Issue by pongib** [RocksonZeta/koa-validate#25]
This is my code 
```js
const getValidation = function* (next) {
  this.checkQuery('limit').optional().len(1, 100).trim().toInt()
  this.checkQuery('offset').optional().len(1, 100).trim().toInt()

  if (this.errors) {
    this.status = 400
    this.body = this.errors
    return
  }
  yield next
}

router.get('/something', getValidation, Ctrl.get)
```
When I send GET without `offset` query params, It will populate error with `TypeError: This library (validator.js) validates strings only`. If I did something wrong just point me to correct please. Thank you.

**Comment by RocksonZeta** [comment]
thanks, this bug has been fixed at 1.0.7  .
